### ISSUE TITLE
Rename library

### ISSUE THREAD

**Issue by f-f** [f-f/googlica#14]
@zudov I propose a renaming of the library: `googlica` -> `gogolica`.

There is a few reasons:
1. The new one will get less hits on google. Also, while googling `googlica`, it gets autocorrected to "google", which is not nice.
2. There is objectively strong ties to the haskell library
3. Allows to refer to Gogol, with pictures and great quotes like this one:
> "You can't imagine how stupid the whole world has grown nowadays."
>
> *Nikolai Vasilievich Gogol*

**Comment by zudov** [comment]
Haha :+1:

(1.) makes it pretty reasonable and the other reasons are pretty useful too.

Some spec-checking part ought to be named ["revisor"](https://en.wikipedia.org/wiki/The_Government_Inspector) if appropriate.
